### ISSUE TITLE
Request: Teensy LC Support

### ISSUE THREAD

**Issue by donpdonp** [apmorton/teensy-template#8]
This template has been great for Teensy 3.1 projects. Has there been any planning or work done to support the new Teensy LC board? (Core MKL26Z64)

**Comment by apmorton** [comment]
I haven't looked into the LC yet (didn't even know about it).
Adding support for it should be as simple as updating the teensy3 directory from paul's cores repo, and then adding a few more lines to the makefile to define the right settings and use the correct linker script.

I don't have a teensy LC to test on, but I could push up some changes so that you can test them.

Otherwise, I will gladly accept a pull request if you want to try it on your own.

Austin

**Comment by donpdonp** [comment]
Hi. I started walking down that path once I noticed Paul's core repo. It was going well until the arm GCC was too old (4.7). The LC is a core-m0plus which is supported in GCC 4.8 and up. The arm gcc builds I found are 32-but. The one in your repo appears to be Paul's build of gcc and is 64bit. Do you know where to refresh these tools from?

**Comment by apmorton** [comment]
I stole them from the teensyduino package IIRC, along with all Paul's custom tools in that directory.

Just unpack the linux version of the teensyduino installer somewhere and copy all the tools.

It would be a good idea to delete the contents of the `tools/arm-none-eabi` folder before copying over the new tools.

**Comment by apmorton** [comment]
see master
